### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by xvolte** [ICBTech/nRF905#3]
Hello,

First of all, I'm using : 

root@yapi:/home/osmc/nRF905# uname -r
**4.4.27-7-osmc**

I also installed the kernel headers by running the following command:

root@yapi:/home/osmc/nRF905# apt-get install rbp2-headers*
Note, selecting 'rbp2-headers-4.4.27-7-osmc' for regex 'rbp2-headers*'
Note, selecting 'rbp2-headers-4.4' for regex 'rbp2-headers*'
Note, selecting 'rbp2-headers' for regex 'rbp2-headers*'
Note, selecting 'rbp2-headers-4.4.27-7-osmc' instead of 'rbp2-headers'
Note, selecting 'rbp2-headers-4.4.27-7-osmc' instead of 'rbp2-headers-4.4'
**The following NEW packages will be installed:
  rbp2-headers-4.4.27-7-osmc**

But now, when i'm in your folder and if i type 'make', i get the following errors :
root@yapi:/home/osmc/nRF905# make
make[1]: Entering directory '/usr/src/rbp2-headers-4.4.27-7-osmc/tools/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/src/rbp2-headers-4.4.27-7-osmc/tools/build'
Makefile:9: recipe for target 'modules' failed
make: *** [modules] Error 2
root@yapi:/home/osmc/nRF905#

what am i doing wrong ?

Thanks in advance,

Best regards,

**Comment by bandigarf** [comment]
Hello,

The primary reason why I went with the `-rpfv` kernel in the instructions is that its package includes **all** files necessary to compile a module for it, which is not true for the default Raspbian kernel (and also for the kernel that you are using).

Apart from switching to the `-rpvf` kernel, you could also try the following:
- Obtain the files from the same place where you got the kernel (maybe there is a separate package containing the `build` directory). I'm not really familiar with OSMC, so I can't really help you with this.
- You might get lucky with `rpi-source` or `sudo modprobe configs` + `zcat /proc/config.gz` to recreate enough of the kernel configuration - something described here http://raspberrypi.stackexchange.com/questions/39845/how-compile-a-loadable-kernel-module-without-recompiling-kernel
- If all else fails, you could build the kernel yourself http://elinux.org/Raspberry_Pi_Kernel_Compilation
